# -*- coding: utf-8 -*-
"""solusi-retail.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wfGmR4FiCeS2r-_EIw2AxHqG64Ft6oi1
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from mlxtend.frequent_patterns import apriori, association_rules
import warnings
import os

warnings.filterwarnings('ignore')

file_name = 'data_penjualan.csv'
if not os.path.exists(file_name):
    for f in os.listdir('.'):
        if f.endswith('.csv'):
            file_name = f
            break

try:
    df = pd.read_csv(file_name, sep=';')
    df.columns = df.columns.str.strip()
    df['tgl_transaksi'] = pd.to_datetime(df['tgl_transaksi'], dayfirst=True)
    df = df.sort_values(['nama_produk', 'tgl_transaksi'])
except Exception as e:
    print(f"Error loading file: {e}")
    exit()

daily_sales = df.groupby(['nama_produk', 'tgl_transaksi'])['total_nilai'].sum().reset_index()
daily_sales['moving_avg'] = daily_sales.groupby('nama_produk')['total_nilai'].transform(lambda x: x.rolling(window=3).mean())
daily_sales['is_rising'] = daily_sales.groupby('nama_produk')['moving_avg'].diff() > 0

def count_consecutive(series):
    return series.groupby((series != series.shift()).cumsum()).cumsum()

daily_sales['consecutive_days'] = daily_sales.groupby('nama_produk')['is_rising'].transform(count_consecutive)

rising_star_names = daily_sales[daily_sales['consecutive_days'] >= 12]['nama_produk'].unique()
df_rising_stars = daily_sales[daily_sales['nama_produk'].isin(rising_star_names)].copy()

results = []
for produk in rising_star_names:
    data_produk = df_rising_stars[df_rising_stars['nama_produk'] == produk].dropna(subset=['moving_avg'])
    if len(data_produk) < 2: continue

    ma_awal = data_produk['moving_avg'].iloc[0]
    ma_akhir = data_produk['moving_avg'].iloc[-1]
    total_penjualan = data_produk['total_nilai'].sum()
    growth_pct = ((ma_akhir / ma_awal) - 1) * 100

    results.append({
        'Nama Produk': produk,
        'Growth %': round(growth_pct, 2),
        'Total Penjualan': int(total_penjualan)
    })

df_final_rising_star = pd.DataFrame(results).sort_values('Growth %', ascending=False)

basket = (df.groupby(['nomor_struk', 'nama_produk'])['jumlah_terjual']
          .sum().unstack().reset_index().fillna(0)
          .set_index('nomor_struk'))

basket_sets = basket.applymap(lambda x: 1 if x >= 1 else 0)
frequent_itemsets = apriori(basket_sets, min_support=0.01, use_colnames=True)
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)

rising_stars_list = df_final_rising_star['Nama Produk'].tolist()
def involve_rising_star(rule_row):
    combined = list(rule_row['antecedents']) + list(rule_row['consequents'])
    return any(item in rising_stars_list for item in combined)

df_packaging = rules[rules.apply(involve_rising_star, axis=1)]
df_packaging = df_packaging[df_packaging['lift'] >= 2]

# Hapus Duplikat Simetris
df_packaging['temp_pair'] = df_packaging.apply(lambda row: tuple(sorted(list(row['antecedents']) + list(row['consequents']))), axis=1)
df_packaging = df_packaging.drop_duplicates(subset=['temp_pair']).drop(columns=['temp_pair'])
df_packaging = df_packaging.sort_values(['lift', 'support'], ascending=False)

df_packaging_final = pd.DataFrame({
    'antecedents': df_packaging['antecedents'].apply(lambda x: ', '.join(list(x))),
    'consequents': df_packaging['consequents'].apply(lambda x: ', '.join(list(x))),
    'support': df_packaging['support'],
    'confidence': df_packaging['confidence'],
    'lift': df_packaging['lift']
})

with pd.ExcelWriter('retail_insight.xlsx', engine='openpyxl') as writer:
    df_final_rising_star.to_excel(writer, sheet_name='Rising Star', index=False)
    df_packaging_final.to_excel(writer, sheet_name='Potential Packaging', index=False)

plt.figure(figsize=(10, 5))
top_3 = df.groupby('nama_produk')['total_nilai'].sum().nlargest(3).index
for p in daily_sales['nama_produk'].unique():
    d = daily_sales[daily_sales['nama_produk'] == p].dropna(subset=['moving_avg'])
    if len(d) == 0: continue
    val = (d['moving_avg'] / d['moving_avg'].iloc[0]) * 100
    if p in rising_star_names:
        plt.plot(d['tgl_transaksi'], val, label=f"Rising Star: {p}", linewidth=2.5)
    elif p in top_3:
        plt.plot(d['tgl_transaksi'], val, label=f"Top: {p}", linestyle='--', alpha=0.6)
plt.title('ANALISIS PERTUMBUHAN RELATIF')
plt.legend(loc='upper left', bbox_to_anchor=(1, 1))
plt.savefig('rising_star_index.png', bbox_inches='tight')
plt.close()

plt.figure(figsize=(10, 5))
for p in rising_star_names:
    d = daily_sales[daily_sales['nama_produk'] == p].dropna(subset=['moving_avg'])
    plt.plot(d['tgl_transaksi'], d['moving_avg'], label=f"Rising Star: {p}", linewidth=2.5)
plt.title('TREN PENJUALAN AKTUAL (MA 3 HARI)')
plt.legend(loc='upper left', bbox_to_anchor=(1, 1))
plt.savefig('rising_star_actual.png', bbox_inches='tight')
plt.close()

print("File retail_insight.xlsx, rising_star_index.png, dan rising_star_actual.png telah dibuat.")